export const search = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Jugoslavija",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Korea(Democratic People Republic of)",
  "Kuwait"
]
export const items = [
  {
    "color": "red",
    "cutpot": "cut",
    "family": "rose",
    "grade": "AA",
    "id": "AIEHO6CUQACVS",
    "note": null,
    "origin": "korea",
    "price": 111,
    "product_id": "AIEHO6CTAACVQ",
    "quantity": 111,
    "unit": "11",
    "variety": "amber",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH3YQACXW",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH32QACXY",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH33QACX2",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH35AACX4",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH36AACX6",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH36QACYA",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH37AACYC",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HEAACYQ",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEHZ47ZAACV4",
    "note": null,
    "origin": "Argentina",
    "price": 222,
    "product_id": "AO5YGADCAADG2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIEQZH4AAACYE",
    "note": null,
    "origin": "Argentina",
    "price": 222,
    "product_id": "AO5YGADCAADG2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HFAACYS",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HGAACYU",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HGQACYW",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HHQACYY",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HIQACY2",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HJQACY4",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HKQACY6",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HMAACZA",
    "note": null,
    "origin": "america",
    "price": 222,
    "product_id": "AIEHZ47XAACV2",
    "quantity": 222,
    "unit": "22",
    "variety": "pearl",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HNAACZC",
    "note": null,
    "origin": "lao",
    "price": 333,
    "product_id": "AIJSZPW6QACZO",
    "quantity": 333,
    "unit": "22",
    "variety": "crystal",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HNAAC8C",
    "note": null,
    "origin": "lao",
    "price": 333,
    "product_id": "AIJSZPW6QACZO",
    "quantity": 333,
    "unit": "22",
    "variety": "crystal",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HNAAC4C",
    "note": null,
    "origin": "lao",
    "price": 333,
    "product_id": "AIJSZPW6QACZO",
    "quantity": 333,
    "unit": "22",
    "variety": "crystal",
    "$errors": {}
  },
  {
    "color": "green",
    "cutpot": "cut",
    "family": "rose",
    "grade": "SS",
    "id": "AIFT72HNAACDZ",
    "note": null,
    "origin": "lao",
    "price": 333,
    "product_id": "AIJSZPW6QACZO",
    "quantity": 333,
    "unit": "22",
    "variety": "crystal",
    "$errors": {}
  }
]
